name: flutter_lab
description: Flutter package for FlutterLab, a UI design tool
version: 0.1.0
repository: https://github.com/flutterlabdev/flutter_lab

topics:
 - ui
 - widgets
 - tool

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  socket_io_client: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

